name: swiftify_repository
description: Repository to get Taylor Swift information
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  api_client:
    git:
      url: https://github.com/AnnaPS/swiftify_server.git
      ref: feat/swiftify_data_source
      path: packages/api_client
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  swiftify_data_source:
    git:
      url: https://github.com/AnnaPS/swiftify_server.git
      ref: feat/swiftify_data_source
      path: packages/swiftify_data_source

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.9.2
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
