name: api_client
description: Generic API client for Dart.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dio: ^5.7.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.24.6
  very_good_analysis: ^5.1.0
