import 'package:flutter/material.dart';

class AppTheme {
  const AppTheme();

  ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff5e5f5c),
      surfaceTint: Color(0xff5e5f5c),
      onPrimary: Color(0xffedece9),
      primaryContainer: Color(0xffedece9),
      onPrimaryContainer: Color(0xff6a6a68),
      secondary: Color(0xff4a3d33),
      onSecondary: Color(0xffedece9),
      secondaryContainer: Color(0xff625449),
      onSecondaryContainer: Color(0xffdcc9bb),
      tertiary: Color(0xff5f5e60),
      onTertiary: Color(0xffedece9),
      tertiaryContainer: Color(0xffeeebed),
      onTertiaryContainer: Color(0xff6b6a6c),
      error: Color(0xffba1a1a),
      onError: Color(0xffedece9),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff93000a),
      surface: Color(0xfffcf8f7),
      onSurface: Color(0xff1c1b1b),
      onSurfaceVariant: Color(0xff444844),
      outline: Color(0xff757874),
      outlineVariant: Color(0xffc5c7c2),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313030),
      inversePrimary: Color(0xffc7c6c4),
      primaryFixed: Color(0xffe3e2df),
      onPrimaryFixed: Color(0xff1b1c1a),
      primaryFixedDim: Color(0xffc7c6c4),
      onPrimaryFixedVariant: Color(0xff464745),
      secondaryFixed: Color(0xfff3dfd0),
      onSecondaryFixed: Color(0xff241a11),
      secondaryFixedDim: Color(0xffd6c3b5),
      onSecondaryFixedVariant: Color(0xff51443a),
      tertiaryFixed: Color(0xffe4e2e4),
      onTertiaryFixed: Color(0xff1b1b1d),
      tertiaryFixedDim: Color(0xffc8c6c8),
      onTertiaryFixedVariant: Color(0xff474648),
      surfaceDim: Color(0xffddd9d8),
      surfaceBright: Color(0xfffcf8f7),
      surfaceContainerLowest: Color(0xffedece9),
      surfaceContainerLow: Color(0xfff7f3f2),
      surfaceContainer: Color(0xfff1edec),
      surfaceContainerHigh: Color(0xffebe7e6),
      surfaceContainerHighest: Color(0xffe5e2e1),
    );
  }

  ThemeData get light {
    return theme(lightScheme());
  }

  ColorScheme lightHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff2b2c2b),
      surfaceTint: Color(0xff5e5f5c),
      onPrimary: Color(0xffedece9),
      primaryContainer: Color(0xff484947),
      onPrimaryContainer: Color(0xffedece9),
      secondary: Color(0xff352a20),
      onSecondary: Color(0xffedece9),
      secondaryContainer: Color(0xff54473c),
      onSecondaryContainer: Color(0xffedece9),
      tertiary: Color(0xff2c2c2e),
      onTertiary: Color(0xffedece9),
      tertiaryContainer: Color(0xff49494b),
      onTertiaryContainer: Color(0xffedece9),
      error: Color(0xff600004),
      onError: Color(0xffedece9),
      errorContainer: Color(0xff98000a),
      onErrorContainer: Color(0xffedece9),
      surface: Color(0xfffcf8f7),
      onSurface: Color(0xff000000),
      onSurfaceVariant: Color(0xff000000),
      outline: Color(0xff2a2d2a),
      outlineVariant: Color(0xff474a46),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313030),
      inversePrimary: Color(0xffc7c6c4),
      primaryFixed: Color(0xff484947),
      onPrimaryFixed: Color(0xffedece9),
      primaryFixedDim: Color(0xff323331),
      onPrimaryFixedVariant: Color(0xffedece9),
      secondaryFixed: Color(0xff54473c),
      onSecondaryFixed: Color(0xffedece9),
      secondaryFixedDim: Color(0xff3c3027),
      onSecondaryFixedVariant: Color(0xffedece9),
      tertiaryFixed: Color(0xff49494b),
      onTertiaryFixed: Color(0xffedece9),
      tertiaryFixedDim: Color(0xff333234),
      onTertiaryFixedVariant: Color(0xffedece9),
      surfaceDim: Color(0xffbbb8b7),
      surfaceBright: Color(0xfffcf8f7),
      surfaceContainerLowest: Color(0xffedece9),
      surfaceContainerLow: Color(0xfff4f0ef),
      surfaceContainer: Color(0xffe5e2e1),
      surfaceContainerHigh: Color(0xffd7d4d3),
      surfaceContainerHighest: Color(0xffc9c6c5),
    );
  }

  ThemeData get lightHighContrast {
    return theme(lightHighContrastScheme());
  }

  ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffedece9),
      surfaceTint: Color(0xffc7c6c4),
      onPrimary: Color(0xff30312f),
      primaryContainer: Color(0xffe3e2df),
      onPrimaryContainer: Color(0xff646562),
      secondary: Color(0xffd6c3b5),
      onSecondary: Color(0xff3a2e25),
      secondaryContainer: Color(0xff625449),
      onSecondaryContainer: Color(0xffdcc9bb),
      tertiary: Color(0xffedece9),
      onTertiary: Color(0xff303032),
      tertiaryContainer: Color(0xffe4e2e4),
      onTertiaryContainer: Color(0xff656466),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff141313),
      onSurface: Color(0xffe5e2e1),
      onSurfaceVariant: Color(0xffc5c7c2),
      outline: Color(0xff8f918d),
      outlineVariant: Color(0xff444844),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe5e2e1),
      inversePrimary: Color(0xff5e5f5c),
      primaryFixed: Color(0xffe3e2df),
      onPrimaryFixed: Color(0xff1b1c1a),
      primaryFixedDim: Color(0xffc7c6c4),
      onPrimaryFixedVariant: Color(0xff464745),
      secondaryFixed: Color(0xfff3dfd0),
      onSecondaryFixed: Color(0xff241a11),
      secondaryFixedDim: Color(0xffd6c3b5),
      onSecondaryFixedVariant: Color(0xff51443a),
      tertiaryFixed: Color(0xffe4e2e4),
      onTertiaryFixed: Color(0xff1b1b1d),
      tertiaryFixedDim: Color(0xffc8c6c8),
      onTertiaryFixedVariant: Color(0xff474648),
      surfaceDim: Color(0xff141313),
      surfaceBright: Color(0xff3a3939),
      surfaceContainerLowest: Color(0xff0e0e0e),
      surfaceContainerLow: Color(0xff1c1b1b),
      surfaceContainer: Color(0xff201f1f),
      surfaceContainerHigh: Color(0xff2a2a29),
      surfaceContainerHighest: Color(0xff353434),
    );
  }

  ThemeData get dark {
    return theme(darkScheme());
  }

  ColorScheme darkHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffedece9),
      surfaceTint: Color(0xffc7c6c4),
      onPrimary: Color(0xff000000),
      primaryContainer: Color(0xffe3e2df),
      onPrimaryContainer: Color(0xff292a29),
      secondary: Color(0xffffede0),
      onSecondary: Color(0xff000000),
      secondaryContainer: Color(0xffd2bfb1),
      onSecondaryContainer: Color(0xff120904),
      tertiary: Color(0xffedece9),
      onTertiary: Color(0xff000000),
      tertiaryContainer: Color(0xffe4e2e4),
      onTertiaryContainer: Color(0xff2a2a2b),
      error: Color(0xffffece9),
      onError: Color(0xff000000),
      errorContainer: Color(0xffffaea4),
      onErrorContainer: Color(0xff220001),
      surface: Color(0xff141313),
      onSurface: Color(0xffedece9),
      onSurfaceVariant: Color(0xffedece9),
      outline: Color(0xffeff1eb),
      outlineVariant: Color(0xffc1c3be),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe5e2e1),
      inversePrimary: Color(0xff474846),
      primaryFixed: Color(0xffe3e2df),
      onPrimaryFixed: Color(0xff000000),
      primaryFixedDim: Color(0xffc7c6c4),
      onPrimaryFixedVariant: Color(0xff101110),
      secondaryFixed: Color(0xfff3dfd0),
      onSecondaryFixed: Color(0xff000000),
      secondaryFixedDim: Color(0xffd6c3b5),
      onSecondaryFixedVariant: Color(0xff180f07),
      tertiaryFixed: Color(0xffe4e2e4),
      onTertiaryFixed: Color(0xff000000),
      tertiaryFixedDim: Color(0xffc8c6c8),
      onTertiaryFixedVariant: Color(0xff111113),
      surfaceDim: Color(0xff141313),
      surfaceBright: Color(0xff51504f),
      surfaceContainerLowest: Color(0xff000000),
      surfaceContainerLow: Color(0xff201f1f),
      surfaceContainer: Color(0xff313030),
      surfaceContainerHigh: Color(0xff3c3b3b),
      surfaceContainerHighest: Color(0xff484646),
    );
  }

  ThemeData get darkHighContrast {
    return theme(darkHighContrastScheme());
  }

  ThemeData theme(ColorScheme colorScheme) => ThemeData(
        useMaterial3: true,
        brightness: colorScheme.brightness,
        colorScheme: colorScheme,
        textTheme: const TextTheme().apply(
          bodyColor: colorScheme.onSurface,
          displayColor: colorScheme.onSurface,
        ),
        scaffoldBackgroundColor: colorScheme.surface,
        canvasColor: colorScheme.surface,
        appBarTheme: AppBarTheme(
          backgroundColor: colorScheme.primary,
          foregroundColor: colorScheme.onPrimary,
        ),
        bottomNavigationBarTheme: BottomNavigationBarThemeData(
          backgroundColor: colorScheme.surface,
          selectedItemColor: colorScheme.primary,
          unselectedItemColor: colorScheme.onSurfaceVariant,
        ),
      );
}
